# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 301fb798e2c5612e895656c341cb1cf1c28dbc53277a6c14ff70dbe4732d2438f0f9850217ee94dee534c46893c561ca42850faf13a7dfbc221e86cb17fd3cf7

test:
  secret_key_base: 3aebe354a7fa2152e1923484cb4bebc7325d6beab7fac185abdbf2b7bce19f421cff206c3cf2386bec7d09dc689c0a7094228bfdfc72068e8b829c42e3d1d1aa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
